name: Filter List Processing

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  process-filter-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python
      run: sudo apt-get install python3

    - name: Run the Python script to remove duplicates
      run: |
        python3 workflows/remove_duplicates.py

    - name: Commit updated filter list
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add filters/unified.txt
        git commit -m "Removed duplicate filters"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

