name: Build Mobile Pro++Mini TIF Medium Filter List

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * *'  # Täglich um 3 Uhr früh
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Combine and Clean Filterlists
        run: |
          mkdir -p filters
          cd filters

          echo "[Adblock Plus 2.0]" > mobile_pro++tif_raw.txt
          echo "! Title: Mobile PRO++Mini TIF Medium Filterlist" >> mobile_pro++tif_raw.txt
          echo "! Author: anonym" >> mobile_pro++tif_raw.txt
          echo "! Description: Mobile-focused PRO++Mini, TIF Medium, and Native Blocker Combo" >> mobile_pro++tif_raw.txt
          echo "! Version: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> mobile_pro++tif_raw.txt
          echo "" >> mobile_pro++tif_raw.txt

          urls=(
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.mini.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.medium.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.apple.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.xiaomi.txt"
          )

          for url in "${urls[@]}"; do
            filename=$(basename "$url")
            echo -e "\n\n! =============== Source: $filename ===============" >> mobile_pro++tif_raw.txt
            curl -s "$url" | grep -vE '^(!|\s*$)' >> mobile_pro++tif_raw.txt
          done

          # Regeln extrahieren, sortieren und Duplikate entfernen
          grep -v '^!' mobile_pro++tif_raw.txt | sort -u > mobile_pro++tif_sorted.txt

          # Metadaten + sortierte Liste kombinieren
          head -n 5 mobile_pro++tif_raw.txt > mobile_pro++tif.txt
          echo "" >> mobile_pro++tif.txt
          cat mobile_pro++tif_sorted.txt >> mobile_pro++tif.txt
          
      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi
      
      - name: Commit & Push
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add filters/mobile_pro++tif.txt
          git commit -m "Update Mobile PRO++Mini TIF Medium filter list"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
