name: Build Clean Filter List with Duplicate Report

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * *'  # Täglich um 3 Uhr früh
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Combine and Analyze Filterlists
        run: |
          mkdir -p filters temp
          cd temp
          
          urls=(
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.mini.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.medium.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.apple.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.xiaomi.txt"
            "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt"
            "https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-ag-online.txt"
            "https://easylist.to/easylist/easyprivacy.txt"
            "https://easylist.to/easylist/easylist.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2023.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2024.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt"
          )

          for url in "${urls[@]}"; do
            curl -s "$url" | grep -vE '^(!|\s*$)' >> combined_raw.txt
          done

          # Duplikate und Clean List erzeugen
          sort combined_raw.txt | uniq -d > ../filters/duplicates.txt
          sort combined_raw.txt | uniq > ../filters/clean_combined.txt

          # Statistiken
          total=$(wc -l < combined_raw.txt)
          unique=$(wc -l < ../filters/clean_combined.txt)
          duplicates=$(wc -l < ../filters/duplicates.txt)

          # Report in die Duplicates-Datei schreiben
          {
            echo "! ===== Duplicate Report ====="
            echo "! Gesamtzahl aller gesammelten Regeln: $total"
            echo "! Einzigartige Regeln nach Bereinigung: $unique"
            echo "! Anzahl der gefundenen Duplikate: $duplicates"
            echo "! =================================="
            echo ""
            cat ../filters/duplicates.txt
          } > ../filters/duplicates.txt

      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi
      
      - name: Commit & Push
        if: success()
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add filters/clean_combined.txt filters/duplicates.txt
          git commit -m "Update Filter List and Duplicate Report"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
