name: Sort Duplicates

permissions:
  contents: write

on:
  workflow_dispatch:  # Manuell starten

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Clean Filterlists
        run: |
          mkdir -p filters temp
          rm -f temp/* filters/*

          urls=(
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.plus.mini.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.medium.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.apple.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.xiaomi.txt"
            "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt"
            "https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-ag-online.txt"
            "https://easylist.to/easylist/easyprivacy.txt"
            "https://easylist.to/easylist/easylist.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2023.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2024.txt"
            "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt"
          )

          for url in "${urls[@]}"; do
            echo "Hole $url"
            curl -s "$url" | grep -vE '^(!|\s*$)' >> temp/combined_raw.txt
          done

          # Doppelte Regeln erkennen
          sort temp/combined_raw.txt | uniq -d > filters/duplicates.txt

          # Saubere Liste erstellen
          sort temp/combined_raw.txt | uniq > filters/clean_combined.txt

          # Kurze Bestätigung
          echo "Listen gebaut: clean_combined.txt & duplicates.txt"
      
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add filters/clean_combined.txt filters/duplicates.txt
          git commit -m "Update Clean Combined and Duplicates"
          git push
